### ISSUE TITLE
Markdown Editor Issues

### ISSUE THREAD

**Issue by daaray** [PyCon/pycon#15]
Consolidating known issues; feel free to break out as needed:
- [x] Preview pane was proposed to be side by side. Out of the box we have `above` and `below` support.  Resolution: let's leave it below
- [ ] CSS tweaks to align toolbar with bootstrapped textareas
- [ ] Admin CSS tweaks to live preview (default admin CSS bleeds into the markdown preview)
- [ ] Bring back h1-h6 support? Markedit has a single heading tool, whereas MarkItUp supported h1 (#) through h6~ish
- [ ]  I'm seeing the text box where I edit as narrower than the toolbar above it and the preview below it.  Partial resolution: #21 
- [x] The help underneath links to a Markdown cheatsheet that demonstrates a bunch of "markdown plus" and "markdown extra" features that our tool doesn't appear to implement. Maybe we can see if there's a switch to turn those on; otherwise, we can add our own help page that only shows the features we implement.  resolution: #19 link to standard markdown page
- [x] Displayed content not matching preview.  E.g. I put in something like:
  # Headline
  
  Text

and in the preview the Headline shows up like an H1, but when I save, the page displays # Headline.  This was in a "box". It looks like we'll need to update this template to render using the same engine: `symposion/templates/boxes/box.html`.  resolution: Fixed in #16.
- [x] HTML in CMS pages was being displayed literally. Fixed in #26 
- [ ] When JS is disabled, raw markdown is rendered. The old editor stored and rendered the calculated HTML
