### ISSUE TITLE
Finaid 8-28 feedback

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#196]
Feedback from 8-28 review of financial aid app, focused on application review:

* [x] Rename Travel Prefered Disbursement field to Disbursement Notes (#199)
* [x] Remove fields:
  * [x] Travel signed
  * [x] Travel check number
  * [x] Tutorial amount
* [x] Add documentation for using templates to email applicants (#201)
* [x] Cut back on capitalization (#197)

**Comment by brandon-rhodes** [comment]
As all of these checkbox items now seem to be completed, I am closing this old issue from 2013.
