### ISSUE TITLE
Financial Aid Feedback

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#508]
https://basecamp.com/1849796/projects/9507827/messages/47174648
- [ ] Python Experience Level: Should be a dropdown. (#538)
- [x] Review Financial Aid Applications should not load all the applications from last year.
- [ ] Sorting only sorts the names on the current page in review financial aid appellations page, not all.  (#538)
- [x] Sorting doesn’t sort correctly (we tried sorting by date — see screenshot. Date field is being sorted lexicographically) (even when sorting just the names on the current page.)  (#538)
- [x] “Grant letter sent” should have a drop-down Yes/No menu (#538)
- [x] “Cash check” should be called payment type (#538)
- [x] “Travel Cash Check” should go away. (#538)
- [ ] Clicked “Requesting more funds”, and submitted a message. The message was added, but did not send the admins an email. 
- [ ] Clicking on “Accept grant” should send a confirmation email to the applicant. If this works the same way as normally submitting a message works, then that’s fine too.
- [ ] “Financial Aid status” should show “Grant offered” as well as “grant requested”.

**Comment by hatlas** [comment]
QA for QA 2016.10 issues:
Python experience dropdown passes QA:
![screen shot 2015-09-16 at 2 35 59 pm](https://cloud.githubusercontent.com/assets/8808771/9914514/4561d6dc-5c80-11e5-86f5-6c7ed97514b1.png)
"Review Financial Aid Applications should not load all the applications from last year." passes QA - only 2015 application appears:
![screen shot 2015-09-16 at 2 46 49 pm](https://cloud.githubusercontent.com/assets/8808771/9914831/c7686eec-5c81-11e5-8eae-b4bc95d192e3.png)
"Sorting only sorts the names on the current page in review financial aid appellations page, not all. (#538)" - this works now. Sorting sorts all names, not just those on current page:
![screen shot 2015-09-16 at 3 23 05 pm](https://cloud.githubusercontent.com/assets/8808771/9915774/ddf3cf94-5c86-11e5-839d-17dae13c2d63.png)
![screen shot 2015-09-16 at 3 23 13 pm](https://cloud.githubusercontent.com/assets/8808771/9915777/dfcea820-5c86-11e5-86de-29e623ee5785.png)
" Sorting doesn’t sort correctly (we tried sorting by date — see screenshot. Date field is being sorted lexicographically) (even when sorting just the names on the current page.) (#538)" - this seems to be working
 “Grant letter sent” should have a drop-down Yes/No menu (#538)" - passes QA
![screen shot 2015-09-16 at 3 20 29 pm](https://cloud.githubusercontent.com/assets/8808771/9915697/82a70b92-5c86-11e5-9a1f-dc9f3223ce04.png)
 “Cash check” should be called payment type (#538) - passes QA
 “Travel Cash Check” should go away. (#538) - passes QA
![screen shot 2015-09-16 at 3 24 13 pm](https://cloud.githubusercontent.com/assets/8808771/9915807/0ac9ba74-5c87-11e5-80b6-c0b64727796b.png)
