### ISSUE TITLE
QA for 2016.11

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#557]
This is on staging now.

* [x] Bug fixes for Education Summit Proposals (#551, #552, #547, #548)
* [x] Fix for uploading PDFs of financial aid receipts (#549, #550)
* [x] Add Caktus logo to footer (#525, #555)
* [x] Update Pycon favicon (#525, #555)

**Comment by hatlas** [comment]
All tasks pass QA. :mount_fuji:
